# Test configuration for development
data:
  root_dir: "./test_data"  # Update with your test data path
  num_workers: 2
  img_size: 1024
  train_split: 0.8

models:
  registry_path: "model_zoo/registry.json"

training:
  batch_size: 2
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0005
  lr_step_size: 5
  patience: 5

eval:
  iou_threshold: 0.5
  pass_fail_config: "config/pass_fail_jj_physical.yaml"

output:
  dir: "test_outputs"